export const candidatesStart = [
  {
    id: 1,
    image: "Boyeon.jpg",
    name: "Boyeon",
    age: "23",
    job: "Convenience Store",
    hobbies: ["videogames", "workout"],
    character: ["bold", "flirty", "extroverted", "fun", "determined"],
    Husband: "",
    Date: "",
    Sex: "",
    Poly: true,
    Rating: 0,
  },
  {
    id: 2,
    image: `Cain.jpg`,
    name: "Cain",
    age: "",
    job: "",
    hobbies: [],
    character: [],
    Husband: "",
    Date: "",
    Sex: "",
    Poly: true,
    Rating: 0,
  },
  {
    id: 3,
    image: `Connor.jpg`,
    name: "Connor",
    age: "",
    job: "",
    hobbies: [],
    character: [],
    Husband: "",
    Date: "",
    Sex: "",
    Poly: true,
    Rating: 0,
  },
  {
    id: 4,
    image: `Fay.jpg`,
    name: "Fay",
    age: "",
    job: "",
    hobbies: [],
    character: [],
    Husband: "",
    Date: "",
    Sex: "",
    Poly: true,
    Rating: 0,
  },
  {
    id: 5,
    image: `Hajun.jpg`,
    name: "Hajun",
    age: "",
    job: "",
    hobbies: [],
    character: [],
    Husband: "",
    Date: "",
    Sex: "",
    Poly: true,
    Rating: 0,
  },
  {
    id: 6,
    image: `Halo.jpg`,
    name: "Halo",
    age: "",
    job: "",
    hobbies: [],
    character: [],
    Husband: "",
    Date: "",
    Sex: "",
    Poly: true,
    Rating: 0,
  },
  {
    id: 7,
    image: `Hyeonwoo.jpg`,
    name: "Hyeonwoo",
    age: "",
    job: "",
    hobbies: [],
    character: [],
    Husband: "",
    Date: "",
    Sex: "",
    Poly: true,
    Rating: 0,
  },
  {
    id: 8,
    image: `Jaemin.jpg`,
    name: "Jaemin",
    age: "",
    job: "",
    hobbies: [],
    character: [],
    Husband: "",
    Date: "",
    Sex: "",
    Poly: true,
    Rating: 0,
  },
  {
    id: 9,
    image: `Minho.jpg`,
    name: "Minho",
    age: "",
    job: "",
    hobbies: [],
    character: [],
    Husband: "",
    Date: "",
    Sex: "",
    Poly: true,
    Rating: 0,
  },
  {
    id: 10,
    image: `One.jpg`,
    name: "One",
    age: "",
    job: "",
    hobbies: [],
    character: [],
    Husband: "",
    Date: "",
    Sex: "",
    Poly: true,
    Rating: 0,
  },
  {
    id: 11,
    image: `Rico.jpg`,
    name: "Rico",
    age: "",
    job: "",
    hobbies: [],
    character: [],
    Husband: "",
    Date: "",
    Sex: "",
    Poly: true,
    Rating: 0,
  },
  {
    id: 12,
    image: `Riley.jpg`,
    name: "Riley",
    age: "",
    job: "",
    hobbies: [],
    character: [],
    Husband: "",
    Date: "",
    Sex: "",
    Poly: true,
    Rating: 0,
  },
];
