export const candidatesStart = [
  {
    id: 1,
    image: "Boyeon.jpg",
    name: "Boyeon",
    age: "23",
    job: "Convenience Store Employee",
    hobbies: ["playing Mobilegames", "Taekwondo", "Photography"],
    character: [
      "flirty",
      "extroverted",
      "fun",
      "energetic",
      "upbeat",
      "kind",
      "family-oriented",
    ],
    boyfriend:
      "Would like someone to bring more romance into his life as well as someone to feel safe with, that he can trust fully. Maybe also someone that is up for adventures and parties",
    meeting: false,
    dateInfo:
      "Would like to go out on a fun date with you. Maybe to a Club to dance the night away together.",
    poly: false,
    rating: 0,
    ratingValues: { looks: 5, hobbies: 5, character: 5, boyfriend: 5 },
  },
  {
    id: 2,
    image: `Cain.jpg`,
    name: "Cain",
    age: "",
    job: "",
    hobbies: [],
    character: [],
    boyfriend: false,
    meeting: false,
    dateInfo: "Let's go on a date",
    message: "Let's have fun together!",
    rating: 0,
    ratingValues: { looks: 5, hobbies: 5, character: 5, boyfriend: 5 },
  },
  {
    id: 3,
    image: `Connor.jpg`,
    name: "Connor",
    age: "",
    job: "",
    hobbies: [],
    character: [],
    boyfriend: false,
    meeting: false,
    dateInfo: "Let's go on a date",
    message: "Let's have fun together!",
    rating: 0,
    ratingValues: { looks: 5, hobbies: 5, character: 5, boyfriend: 5 },
  },
  {
    id: 4,
    image: `Fay.jpg`,
    name: "Fay",
    age: "",
    job: "",
    hobbies: [],
    character: [],
    boyfriend: false,
    meeting: false,
    dateInfo: "Let's go on a date",
    message: "Let's have fun together!",
    rating: 0,
    ratingValues: { looks: 5, hobbies: 5, character: 5, boyfriend: 5 },
  },
  {
    id: 5,
    image: `Hajun.jpg`,
    name: "Hajun",
    age: "",
    job: "",
    hobbies: [],
    character: [],
    boyfriend: false,
    meeting: false,
    dateInfo: "Let's go on a date",
    message: "Let's have fun together!",
    rating: 0,
    ratingValues: { looks: 5, hobbies: 5, character: 5, boyfriend: 5 },
  },
  {
    id: 6,
    image: `Halo.jpg`,
    name: "Halo",
    age: "",
    job: "",
    hobbies: [],
    character: [],
    boyfriend: false,
    meeting: false,
    dateInfo: "Let's go on a date",
    message: "Let's have fun together!",
    rating: 0,
    ratingValues: { looks: 5, hobbies: 5, character: 5, boyfriend: 5 },
  },
  {
    id: 7,
    image: `Hyeonwoo.jpg`,
    name: "Hyeonwoo",
    age: "",
    job: "",
    hobbies: [],
    character: [],
    boyfriend: false,
    meeting: false,
    dateInfo: "Let's go on a date",
    message: "Let's have fun together!",
    rating: 0,
    ratingValues: { looks: 5, hobbies: 5, character: 5, boyfriend: 5 },
  },
  {
    id: 8,
    image: `Jaemin.jpg`,
    name: "Jaemin",
    age: "",
    job: "",
    hobbies: [],
    character: [],
    boyfriend: false,
    meeting: false,
    dateInfo: "Let's go on a date",
    message: "Let's have fun together!",
    rating: 0,
    ratingValues: { looks: 5, hobbies: 5, character: 5, boyfriend: 5 },
  },
  {
    id: 9,
    image: `Minho.jpg`,
    name: "Minho",
    age: "",
    job: "",
    hobbies: [],
    character: [],
    boyfriend: false,
    meeting: false,
    dateInfo: "Let's go on a date",
    message: "Let's have fun together!",
    rating: 0,
    ratingValues: { looks: 5, hobbies: 5, character: 5, boyfriend: 5 },
  },
  {
    id: 10,
    image: `One.jpg`,
    name: "One",
    age: "",
    job: "",
    hobbies: [],
    character: [],
    boyfriend: false,
    meeting: false,
    dateInfo: "Let's go on a date",
    message: "Let's have fun together!",
    rating: 0,
    ratingValues: { looks: 5, hobbies: 5, character: 5, boyfriend: 5 },
  },
  {
    id: 11,
    image: `Rico.jpg`,
    name: "Rico",
    age: "",
    job: "",
    hobbies: [],
    character: [],
    boyfriend: false,
    meeting: false,
    dateInfo: "Let's go on a date",
    message: "Let's have fun together!",
    rating: 0,
    ratingValues: { looks: 5, hobbies: 5, character: 5, boyfriend: 5 },
  },
  {
    id: 12,
    image: `Riley.jpg`,
    name: "Riley",
    age: "",
    job: "",
    hobbies: [],
    character: [],
    boyfriend: false,
    meeting: false,
    dateInfo: "Let's go on a date",
    message: "Let's have fun together!",
    rating: 0,
    ratingValues: { looks: 5, hobbies: 5, character: 5, boyfriend: 5 },
  },
];
